title: "Aaisha says 👋🏽🌎"
description: "Where is Aaisha's 🧠 right now?"
baseurl: ""
url: "https://aireheart.github.io/"


nav:
  - title: "🪼 Home"
    url: /
  - title: "🪶 Blog"
    url: /blog/
  - title: "🔨 Projects"
    url: /projects/
  - title: "📖 Bookshelf"
    url: /bookshelf/
  - title: "🏛️ About"
    url: /about/

markdown: kramdown
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
