title: "Aaisha says 👋🏽🌎"
description: "Where is Aaisha's 🧠 right now?"
baseurl: ""
url: "https://aireheart.github.io/"


# Add this line for the new navbar brand text
navbar_brand: "Aaisha says 👋🏽🌎" # <--- YOUR NEW NAVBAR TEXT HERE

nav:
  - title: "🪼 Home"
    url: /
  - title: "🪶 Blog"
    url: /blog/
  - title: "🔨 Projects"
    url: /projects/
  - title: "🌋 Adventures"
    url: /adventures/
  - title: "🫧 Whimsy"
    url: /whimsy/
  - title: "📖 Bookshelf"
    url: /bookshelf/
  - title: "🏛️ About"
    url: /about/


markdown: kramdown
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
